"""記録の検証器 scripts/review-record.py の検査の表（期待は手で書く。検証器を走らせた出力から作らない）。

1 行が tests/run.sh の review-record.py の節の ok 行 1 件に当たる。欄:
- id: pytest の id（行の並べ順に依らない名前。同じ記録を複数の行が読むときは、何を見るかの接尾辞を付ける）
- args: 検証器に渡す引数。素の名前は壊した記録の置き場（broken_records.write_all の <work>）の下、repo: で始まる物はリポジトリの根の下
- exit: 期待する終了コード（0 = 阻害なし / 1 = 阻害あり / 2 = 記録が不正）
- want: 出力に在るべき文言（ANY は終了コードだけを見る）。exit 2 は標準エラー、0 と 1 は標準出力に在ることを求める
- was: 台本の検査の説明文。台帳（ledger.py）が台本の行と (exit, want, was) の多重集合で突き合わせる
- where: inproc（同じプロセス）か smoke（子プロセス。再帰の深さが環境で変わる 1 件）

台本の側（tests/run.sh）は、腕の証明が CI で済むまで残す。移し終えるまでは、片方を直したらもう片方も直す——ずれは
台帳の突き合わせ（test_review_record.py の test_ledger_matches_script）が赤にする。
"""
import collections

ANY = "__any_output__"   # tests/run.sh の ANY_OUTPUT と同じ番兵
Case = collections.namedtuple("Case", "id args exit want was where", defaults=("inproc",))

CASES = [
    Case("tmpl-1-no-prev", ("tmpl-1",), 1, "前ラウンドの記録が無い",
         "round-1 だけの記録は、比較の欠落を阻害要因に数える"),
    Case("tmpl-12-prev-blockers", ("tmpl-12",), 1, "前ラウンドに阻害要因が 4 件あった",
         "解消した直後のラウンドは連続 2 ラウンドの 1 ラウンド目"),
    Case("tmpl-1-fresh-mark", ("tmpl-1",), 1, "（今ラウンドに立った問い——再審は次の周）",
         "問いが立った周には帰属せず、印だけが付く"),
    Case("tmpl-12-grown-scalars", ("tmpl-12",), 1, "増えた scalar（阻害要因ではない。相殺する削除があるか R1 に見せろ）:\n  - scalar 'doc_lines': 120 → 135\n  - scalar 'comment_ratio_pct': 18 → 21\n持ち越し",
         "増えた scalar だけを、増えた scalar の節に出す"),
    Case("hist-two-rounds", ("hist",), 0, "連続 2 ラウンド",
         "2 ラウンド続けて阻害なしなら exit 0"),
    Case("hist-not-convergence", ("hist",), 0, "これは収束の宣言ではない",
         "阻害なしを収束と名乗らない"),
    Case("hist-carry-age", ("hist",), 0, "素材 prior_decisions: round 1 の判定を流用（2 ラウンド前）",
         "持ち越しは実際に見たラウンドと古さを見せる"),
    Case("drop-material", ("drop-material",), 2, "素材 'hygiene' の返答が無い",
         "不正な記録は 1 と区別して落ちる: drop-material"),
    Case("drop-defer-reason", ("drop-defer-reason",), 2, "defer に構造的理由が無い",
         "不正な記録は 1 と区別して落ちる: drop-defer-reason"),
    Case("drop-base", ("drop-base",), 2, "必須の欄 'base' が無い",
         "不正な記録は 1 と区別して落ちる: drop-base"),
    Case("drop-round", ("drop-round",), 2, "必須の欄 'round' が無い",
         "不正な記録は 1 と区別して落ちる: drop-round"),
    Case("bad-base", ("bad-base",), 2, "base が違う",
         "不正な記録は 1 と区別して落ちる: bad-base"),
    Case("bad-round", ("bad-round",), 2, "ファイル名の番号と違う",
         "不正な記録は 1 と区別して落ちる: bad-round"),
    Case("bad-status", ("bad-status",), 2, "status が不正",
         "不正な記録は 1 と区別して落ちる: bad-status"),
    Case("clean-without-checked", ("clean-without-checked",), 2, "'checked' が要る",
         "不正な記録は 1 と区別して落ちる: clean-without-checked"),
    Case("bad-label", ("bad-label",), 2, "label が不正",
         "不正な記録は 1 と区別して落ちる: bad-label"),
    Case("drop-key", ("drop-key",), 2, "key が無い",
         "不正な記録は 1 と区別して落ちる: drop-key"),
    Case("drop-reviews", ("drop-reviews",), 2, "必須の欄 'reviews' が無い",
         "不正な記録は 1 と区別して落ちる: drop-reviews"),
    Case("drop-review-R3", ("drop-review-R3",), 2, "R3 の verdict が無い",
         "不正な記録は 1 と区別して落ちる: drop-review-R3"),
    Case("bad-review-status", ("bad-review-status",), 2, "R1 の status が不正",
         "不正な記録は 1 と区別して落ちる: bad-review-status"),
    Case("review-only-R2", ("review-only-R2",), 2, "R1 は premise-invalid にできない",
         "不正な記録は 1 と区別して落ちる: review-only-R2"),
    Case("review-only-R34", ("review-only-R34",), 2, "R1 は not_applicable にできない",
         "不正な記録は 1 と区別して落ちる: review-only-R34"),
    Case("pass-without-reason", ("pass-without-reason",), 2, "R3 は status=pass なので 'reason' が要る",
         "不正な記録は 1 と区別して落ちる: pass-without-reason"),
    Case("carry-without-from", ("carry-without-from",), 2, "'from_round' が要る",
         "不正な記録は 1 と区別して落ちる: carry-without-from"),
    Case("carry-from-future", ("carry-from-future",), 2, "今ラウンド（2）より前でない",
         "不正な記録は 1 と区別して落ちる: carry-from-future"),
    Case("carry-from-not-applicable", ("carry-from-not-applicable",), 2, "前ラウンドが not_applicable なので持ち越せない",
         "不正な記録は 1 と区別して落ちる: carry-from-not-applicable"),
    Case("not-object", ("not-object",), 2, "記録の最上位が object でない",
         "不正な記録は 1 と区別して落ちる: not-object"),
    Case("bad-round-type", ("bad-round-type",), 2, "'round' が整数でない",
         "不正な記録は 1 と区別して落ちる: bad-round-type"),
    Case("bad-round-bool", ("bad-round-bool",), 2, "'round' が整数でない",
         "不正な記録は 1 と区別して落ちる: bad-round-bool"),
    Case("round-below-one", ("round-below-one",), 2, "'round' が 1 以上でない",
         "不正な記録は 1 と区別して落ちる: round-below-one"),
    Case("bad-materials-type", ("bad-materials-type",), 2, "'materials' が object でない",
         "不正な記録は 1 と区別して落ちる: bad-materials-type"),
    Case("bad-units-type", ("bad-units-type",), 2, "'units' が配列でない",
         "不正な記録は 1 と区別して落ちる: bad-units-type"),
    Case("bad-unit-type", ("bad-unit-type",), 2, "units[0] が object でない",
         "不正な記録は 1 と区別して落ちる: bad-unit-type"),
    Case("bad-reviews-type", ("bad-reviews-type",), 2, "'reviews' が object でない",
         "不正な記録は 1 と区別して落ちる: bad-reviews-type"),
    Case("bad-from-round-type", ("bad-from-round-type",), 2, "'from_round' は数で書け",
         "不正な記録は 1 と区別して落ちる: bad-from-round-type"),
    Case("bad-scalars-type", ("bad-scalars-type",), 2, "'scalars' が object でない",
         "不正な記録は 1 と区別して落ちる: bad-scalars-type"),
    Case("null-scalars", ("null-scalars",), 2, "'scalars' が object でない",
         "不正な記録は 1 と区別して落ちる: null-scalars"),
    Case("unhashable-status", ("unhashable-status",), 2, "想定外の例外（TypeError）",
         "不正な記録は 1 と区別して落ちる: unhashable-status"),
    Case("unhashable-key", ("unhashable-key",), 2, "想定外の例外（TypeError）",
         "前ラウンドの key が unhashable でも 1 と区別して落ちる"),
    Case("r1-carry", ("r1-carry",), 2, "今ラウンド（1）より前でない",
         "初回ラウンドに持ち越しは書けない"),
    Case("carry-chain-broken", ("carry-chain-broken",), 2, "持ち越しが連鎖していない",
         "前ラウンドとの突合: carry-chain-broken"),
    Case("review-carry-chain-broken", ("review-carry-chain-broken",), 2, "R2 の from_round（1）が前ラウンド（2）でない",
         "前ラウンドとの突合: review-carry-chain-broken"),
    Case("reopen-without-evidence", ("reopen-without-evidence",), 2, "reopen_evidence が無い",
         "前ラウンドとの突合: reopen-without-evidence"),
    Case("reopen-with-evidence", ("reopen-with-evidence",), 1, "既受容 defer の再審。新証拠: 本番ログで上限超過のクエリを 3 件観測",
         "前ラウンドとの突合: reopen-with-evidence"),
    Case("skip-PR", ("skip-PR",), 1, "R3 が not_applicable だが、P-R への到達を妨げる阻害要因が記録に無い",
         "前ラウンドとの突合: skip-PR"),
    Case("redesign", ("redesign",), 1, "R2 が redesign-needed",
         "前ラウンドとの突合: redesign"),
    Case("premise-invalid", ("premise-invalid",), 1, "収束を宣言せずユーザーに諮れ",
         "前ラウンドとの突合: premise-invalid"),
    Case("unverifiable", ("unverifiable",), 1, "収束を宣言せずユーザーに諮れ",
         "前ラウンドとの突合: unverifiable"),
    Case("review-not-run", ("review-not-run",), 1, "R4 が not_run",
         "前ラウンドとの突合: review-not-run"),
    Case("defer-dropped-ledger", ("defer-dropped",), 0, "台帳には残る",
         "前ラウンドとの突合: defer-dropped"),
    Case("defer-dropped-fork", ("defer-dropped",), 0, "[人へ] fork",
         "前ラウンドとの突合: defer-dropped"),
    Case("material-awaiting", ("material-awaiting",), 1, "素材 'consistency' が人の起動待ち",
         "前ラウンドとの突合: material-awaiting"),
    Case("material-not-run", ("material-not-run",), 1, "素材 'hygiene' が未実施",
         "前ラウンドとの突合: material-not-run"),
    Case("dup-key", ("dup-key",), 2, "突合の識別子なので 1 ラウンドに 1 つ",
         "前ラウンドとの突合: dup-key"),
    Case("found-no-units", ("found-no-units",), 1, "素材が found なのに units が空",
         "前ラウンドとの突合: found-no-units"),
    Case("stuck", ("stuck",), 1, "残存——過去のラウンドにも在った",
         "同じ [block] キーが 2 ラウンド残れば残存の印を出す"),
    Case("q-split-on-do-now", ("q-split-on-do-now",), 2, "split の origin / depends が [block] / do-now",
         "問いの台帳: q-split-on-do-now"),
    Case("q-split-on-block", ("q-split-on-block",), 2, "split の origin / depends が [block] / do-now",
         "問いの台帳: q-split-on-block"),
    Case("q-bad-kind", ("q-bad-kind",), 2, "kind が不正",
         "問いの台帳: q-bad-kind"),
    Case("q-bad-status", ("q-bad-status",), 2, "status が不正",
         "問いの台帳: q-bad-status"),
    Case("q-without-reason", ("q-without-reason",), 2, "'reason' が要る",
         "問いの台帳: q-without-reason"),
    Case("q-fork-one-option", ("q-fork-one-option",), 2, "options は選択肢 2 つ以上の配列",
         "問いの台帳: q-fork-one-option"),
    Case("q-resolved-without-resolution", ("q-resolved-without-resolution",), 2, "'resolution' が要る",
         "問いの台帳: q-resolved-without-resolution"),
    Case("q-origin-missing", ("q-origin-missing",), 2, "origin が今ラウンドの units にも defer 台帳にも無い",
         "問いの台帳: q-origin-missing"),
    Case("q-awaiting-unlisted", ("q-awaiting-unlisted",), 2, "素材 'main_path_observation' が awaiting_human なのに問いの台帳に無い",
         "問いの台帳: q-awaiting-unlisted"),
    Case("q-awaiting-origin-clean", ("q-awaiting-origin-clean",), 2, "awaiting の origin 'hygiene' が awaiting_human でない",
         "問いの台帳: q-awaiting-origin-clean"),
    Case("q-review-unlisted", ("q-review-unlisted",), 2, "R1 が unverifiable なのに問いの台帳に無い",
         "問いの台帳: q-review-unlisted"),
    Case("q-premise-origin-mismatch", ("q-premise-origin-mismatch",), 2, "premise の origin R2 が premise-invalid でない",
         "問いの台帳: q-premise-origin-mismatch"),
    Case("q-dup-key", ("q-dup-key",), 2, "の key が重複: x",
         "問いの台帳: q-dup-key"),
    Case("q-legacy-ask-human", ("q-legacy-ask-human",), 2, "人に聞く候補は questions（問いの台帳）に",
         "問いの台帳: q-legacy-ask-human"),
    Case("q-not-list", ("q-not-list",), 2, "'questions' が配列でない",
         "問いの台帳: q-not-list"),
    Case("q-drop", ("q-drop",), 2, "必須の欄 'questions' が無い",
         "問いの台帳: q-drop"),
    Case("q-not-object", ("q-not-object",), 2, "questions[2] が object でない",
         "問いの台帳: q-not-object"),
    Case("q-no-key", ("q-no-key",), 2, "に key が無い（周をまたぐ突合に使う",
         "問いの台帳: q-no-key"),
    Case("q-empty-reason", ("q-empty-reason",), 2, "'reason' が空（きっかけ・根拠を書け）",
         "問いの台帳: q-empty-reason"),
    Case("q-depends-type", ("q-depends-type",), 2, "depends は、この答え待ちで手を止めるユニットの key の配列",
         "問いの台帳: q-depends-type"),
    Case("q-fork-options-type", ("q-fork-options-type",), 2, "options は選択肢 2 つ以上の配列",
         "問いの台帳: q-fork-options-type"),
    Case("q-origin-field-missing", ("q-origin-field-missing",), 2, "なので origin（units の key）が要る",
         "問いの台帳: q-origin-field-missing"),
    Case("q-awaiting-origin-not-material", ("q-awaiting-origin-not-material",), 2, "なので origin は素材名",
         "問いの台帳: q-awaiting-origin-not-material"),
    Case("q-review-origin-not-r", ("q-review-origin-not-r",), 2, "なので origin は R1〜R4",
         "問いの台帳: q-review-origin-not-r"),
    Case("q-thrash-with-origin", ("q-thrash-with-origin",), 2, "なので origin / depends を持てない",
         "問いの台帳: q-thrash-with-origin"),
    Case("q-thrash-with-depends", ("q-thrash-with-depends",), 2, "なので origin / depends を持てない",
         "問いの台帳: q-thrash-with-depends"),
    Case("q-awaiting-depends-missing", ("q-awaiting-depends-missing",), 2, "depends が今ラウンドの units にも defer 台帳にも無い",
         "問いの台帳: q-awaiting-depends-missing"),
    Case("q-fork-options-empty-item", ("q-fork-options-empty-item",), 2, "options は選択肢 2 つ以上の配列",
         "問いの台帳: q-fork-options-empty-item"),
    Case("q-depends-item-type", ("q-depends-item-type",), 2, "depends は、この答え待ちで手を止めるユニットの key の配列",
         "問いの台帳: q-depends-item-type"),
    Case("q-premise-unlisted", ("q-premise-unlisted",), 2, "R2 が premise-invalid なのに問いの台帳に無い",
         "問いの台帳: q-premise-unlisted"),
    Case("q-review-origin-status-unverifiable", ("q-review-origin-status-unverifiable",), 2, "の origin R2 が unverifiable でない",
         "問いの台帳: q-review-origin-status-unverifiable"),
    Case("q-no-open-via-depends", ("q-no-open-via-depends",), 2, "rule の origin / depends が [block] / do-now",
         "問いの台帳: q-no-open-via-depends"),
    Case("q-awaiting-listed-resolved", ("q-awaiting-listed-resolved",), 2, "が awaiting_human なのに問いの台帳に無い",
         "問いの台帳: q-awaiting-listed-resolved"),
    Case("q-unhashable-key", ("q-unhashable-key",), 2, "想定外の例外（TypeError）",
         "問いの台帳: q-unhashable-key"),
    Case("q-dropped", ("q-dropped",), 2, "前ラウンドの問い（held）が今ラウンドの台帳に無い",
         "保留した問いは黙って落とせない"),
    Case("q-dropped-escalate", ("q-dropped-escalate",), 2, "前ラウンドの問い（escalate）が今ラウンドの台帳に無い",
         "人へ回した問いも黙って落とせない"),
    Case("q-depends-missing", ("q-depends-missing",), 2, "depends が今ラウンドの units にも defer 台帳にも無い",
         "出どころの実在検査は depends にも当たる（綴り違いが黙って無効にならない）"),
    Case("q-stuck-decided", ("q-stuck-decided",), 1, "[block] 未解消",
         "決着しても出どころが開いているうちは decided で、台帳から降りない（要求を満たす）"),
    Case("q-resolved-while-open", ("q-resolved-while-open",), 2, "出どころが [block] / do-now のまま resolved",
         "出どころが開いたまま resolved と書けない（1 件置いて要求を永久に黙らせる形を塞ぐ）"),
    Case("q-stuck-other-kind", ("q-stuck-other-kind",), 2, "2 ラウンド連続の残存＝stuck）のに問いの台帳に無い",
         "出どころを持たない種類を置いても stuck の振り分け要求は満たされない"),
    Case("human-repeat-attributed", ("human-repeat",), 1, "残る阻害要因は保留の問いに帰属するものだけ（1 件）",
         "R1〜R4 の人に諮る verdict も保留の問いに帰属する"),
    Case("q-material-attribution", ("q-material-attribution",), 1, "（保留の問いに帰属——答えを待っている）",
         "人の起動待ちの素材も保留の問いに帰属する"),
    Case("q-origin-missing-round1", ("q-origin-missing-round1",), 2, "origin が今ラウンドの units にも defer 台帳にも無い",
         "出どころの実在検査は round 1 にも掛かる"),
    Case("q-premise-not-escalate", ("q-premise-not-escalate",), 1, "保留の問いに帰属する阻害要因 1 件は聞くのを待て——帰属しない 1 件を先に直せ",
         "前提不成立でも、問いが held のうちは短絡しない（載せた周には聞かない）"),
    Case("q-escalate-not-premise", ("q-escalate-not-premise",), 1, "残る阻害要因は保留の問いに帰属するものだけ（1 件）",
         "premise 以外の escalate では前提不成立を出さない"),
    Case("q-stuck-unlisted", ("q-stuck-unlisted",), 2, "2 ラウンド連続の残存＝stuck）のに問いの台帳に無い",
         "同じ [block] が 3 周続けば台帳への記載を要求する"),
    Case("q-stuck-listed-ask", ("q-stuck-listed",), 1, "残る阻害要因は保留の問いに帰属するものだけ（1 件）",
         "残る阻害が保留の問いだけなら「聞く時」を出す"),
    Case("q-fresh", ("q-fresh",), 1, "（今ラウンドに立った問い——再審は次の周）",
         "同じ形でも、問いが立った周には帰属せず印だけが付く（立った周には聞かない）"),
    Case("q-resolved-is-work", ("q-resolved-is-work",), 1, "帰属しない 1 件を先に直せ",
         "ループが決めた問い（decided）の阻害要因は仕事であって、聞く時ではない"),
    Case("q-stuck-listed-mark", ("q-stuck-listed",), 1, "（保留の問いに帰属——答えを待っている）",
         "帰属する阻害要因の行に印が付く"),
    Case("q-mixed", ("q-mixed",), 1, "帰属しない 1 件を先に直せ",
         "帰属しない阻害が残るうちは聞かない"),
    Case("tmpl-1-do-now-heading", ("tmpl-1",), 1, "[suggest] do-now 未対応",
         "do-now の行は [block] と別の見出しで出る"),
    Case("q-depends", ("q-depends",), 1, "残る阻害要因は保留の問いに帰属するものだけ（2 件）",
         "depends に挙げたユニットの阻害も問いに帰属する"),
    Case("q-premise-escalate", ("q-premise-escalate",), 1, "前提不成立が確定（escalate）",
         "premise の escalate は他の阻害の帰属を問わず「聞く時」"),
    Case("domain-separation", ("domain-separation",), 2, "2 ラウンド連続の残存＝stuck）のに問いの台帳に無い: R2",
         "unit の key が R の名前と同じでも、別の域の問いはそのユニットを指したことにならない"),
    Case("q-new-r1-carried", ("q-new-r1-carried",), 2, "台帳の未決の問いが前ラウンドから変わったのに R1 が carried_over",
         "問いが載った周に R1 を持ち越した記録は不正"),
    Case("q-swap-r1-carried", ("q-swap-r1-carried",), 2, "台帳の未決の問いが前ラウンドから変わったのに R1 が carried_over",
         "同じ key のまま中身を総取り替えした周も、R1 を持ち越せない"),
    Case("q-reopen-r1-carried", ("q-reopen-r1-carried",), 2, "台帳の未決の問いが前ラウンドから変わったのに R1 が carried_over",
         "ループが決めた問いが未決に戻った周も、R1 を持ち越せない"),
    Case("q-new-r1-ran", ("q-new-r1-ran",), 1, "[block] 未解消",
         "同じ形でも R1 を走らせていれば通る（対照）"),
    Case("q-carried-r1-carried", ("q-carried-r1-carried",), 1, "[block] 未解消",
         "持ち越した問いだけの周は R1 も持ち越してよい（縛るのは新しく載った問い）"),
    Case("name-case", ("name-case",), 2, "は記録の名前でない",
         "大小が違うだけのファイルを黙って捨てない"),
    Case("name-unidigit", ("name-unidigit",), 2, "は記録の名前でない",
         "桁の異体字のファイル名も黙って受理せず、黙って捨てもしない"),
    Case("name-tail", ("name-tail",), 2, "は記録の名前でない",
         "正規表現の軸に載らない綴りでも、最新ラウンドを黙って捨てない"),
    Case("name-ok", ("name-ok",), 1, "前ラウンドの記録が無い",
         "退避先のディレクトリと OS の成果物では鳴らさない（対照）"),
    Case("q-thrash-silent", ("q-thrash-silent",), 1, "台帳に未決の問いが 1 件（うち人へ 0 件）",
         "出どころで手を止めない問いだけが残る周も、台帳が黙って終わらない"),
    Case("q-stuck-via-depends", ("q-stuck-via-depends",), 2, "2 ラウンド連続の残存＝stuck）のに問いの台帳に無い",
         "連鎖のキーを depends に並べても stuck の振り分け要求は満たされない（見るのは origin）"),
    Case("stuck-window-slide", ("stuck-window-slide",), 2, "round 4: 同じ [block] が 3 ラウンドの記録に続けて在る",
         "3 周の窓は滑る（連鎖が 1 周のびると、次の組で要求が立つ）"),
    Case("stuck-two-rounds", ("stuck-two-rounds",), 1, "（残存——過去のラウンドにも在った）",
         "2 周の残存では、まだ台帳への記載を要求しない（対照）"),
    Case("q-resolved-origin-gone", ("q-resolved-origin-gone",), 1, "[block] 未解消",
         "ループが決めた問いの出どころは、記録から消えていてよい"),
    Case("q-resolved-split-open", ("q-resolved-split-open",), 1, "[block] 未解消",
         "ループが決めた split（decided）は、開いた [block] を指していてよい"),
    Case("q-origin-missing-mid", ("q-origin-missing-mid",), 2, "round 2: questions[0] の origin",
         "出どころの実在検査は中間のラウンドにも掛かる"),
    Case("mixed-base", ("mixed-base",), 2, "混ざっていないか",
         "別レビューの記録が混ざったら、退避の案内を出して止まる"),
    Case("block-dropped", ("block-dropped",), 1, "過去のラウンドの [block] で今ラウンドの記録に無いキー",
         "前ラウンドの [block] が記録から消えたら報告する（defer 側との非対称を消す）"),
    Case("carry-from-human", ("carry-from-human",), 2, "前ラウンドが unverifiable なので持ち越せない",
         "人に諮る verdict を持ち越すと記録の不正になる（阻害要因から消えるため）"),
    Case("human-repeat-counted", ("human-repeat",), 1, "R1 が unverifiable（収束を宣言せずユーザーに諮れ）",
         "人に諮る verdict は、同じ値を書き直せば毎ラウンド数えられる"),
    Case("round-zero", ("round-zero",), 2, "1 から始まる番号でない",
         "round-0.json を黙って捨てない"),
    Case("round-dup", ("round-dup",), 2, "同じ番号",
         "ゼロ詰めの別名が同じ番号に潰れるのを落とす"),
    Case("count-zero", ("count-zero",), 1, "収束を妨げるもの",
         "count: 0 を「値が無い」と言わない"),
    Case("checked-empty", ("checked-empty",), 2, "が空（何を見たかを書け）",
         "空文字は欠落と分けて診断する"),
    Case("from-round-zero", ("from-round-zero",), 2, "from_round が 1 以上でない",
         "存在しないラウンド 0 からの流用を落とす（外すと素材を一度も見ずに収束できる）"),
    Case("stuck-window-width", ("stuck-window-width",), 1, "（残存——過去のラウンドにも在った）",
         "連鎖が 2 周ぶんなら、3 周の窓では台帳への記載を要求しない（窓の幅を測る）"),
    Case("badenc", ("badenc",), 2, "UTF-8 として読めない",
         "UTF-8 でない記録は「開けない」「JSON でない」と別の診断で落ちる"),
    Case("checked-false", ("checked-false",), 2, "が空（何を見たかを書け）",
         "縮退値（false / [] / {}）で明示返答の欄を埋められない"),
    Case("checked-number", ("checked-number",), 2, "が空（何を見たかを書け）",
         "文を要求する欄に数を書いても「埋まっている」にならない"),
    Case("ledger-gap", ("ledger-gap",), 2, "reopen_evidence が無い",
         "1 ラウンド記録から落としても、台帳は全ラウンドの和なので再審を止める"),
    Case("hist-history", ("hist",), 0, "履歴（round 1〜3",
         "ディレクトリを渡すと全ラウンドの履歴を出す"),
    Case("hist-question-ledger", ("hist",), 0, "問いの台帳（人に聞く候補。載せた周には聞かない",
         "台帳の問いは阻害要因にせず、人に聞く候補として出す"),
    Case("hist-question-timeline", ("hist",), 0, "r1:held(awaiting) → r2:resolved(awaiting) → r3:—",
         "問いの推移を履歴に出す（決めた問いは次の周から消えてよい）"),
    Case("hist-question-counts", ("hist",), 0, "問いの台帳の件数（保留・人へ・ループが決めた）: 1・0・0 → 1・0・1 → 1・1・0",
         "台帳の件数の推移を出す"),
    Case("hist-open-questions", ("hist",), 0, "台帳に未決の問いが 2 件（うち人へ 1 件）",
         "阻害要因が 0 でも、台帳に未決が残っていれば判定行がそう言う"),
    Case("hist-owed-counts", ("hist",), 0, "要対応（[block]＋do-now）の件数: 3 → 0 → 0",
         "要対応の件数の推移を出す"),
    Case("hist-gap", ("hist-gap",), 2, "round-2.json が無い",
         "連番に穴があれば履歴を出さずに落ちる"),
    Case("hist-return", ("hist-return",), 0, "r1:block → r2:— → r3:nit（消えて 1 回戻った）",
         "直したはずのキーが戻れば履歴に印を付ける"),
    Case("hist-first-seen-not-returned", ("hist",), 0, "r1:— → r2:suggest/defer → r3:suggest/defer\n",
         "初出のキーを「戻った」と数えない（注記が付かない）"),
    Case("truncated", ("truncated",), 2, "JSON として読めない",
         "壊れた JSON は 1 と区別して落ちる"),
    Case("does-not-exist", ("does-not-exist",), 2, "ディレクトリでない",
         "記録のディレクトリでないものを渡したら 1 と区別して落ちる"),
    Case("unreadable", ("unreadable",), 2, "開けない",
         "読めない記録は 1 と区別して落ちる"),
    Case("no-args", (), 2, ANY,
         "引数なしは 1 と区別して落ちる"),
    Case("too-many-args", ("tmpl-12", "repo:templates/round-1.example.json"), 2, ANY,
         "引数が多すぎる場合も 1 と区別して落ちる"),
    Case("deep", ("deep",), 2, ANY,
         "深いネストの JSON も 1 と区別して落ちる（経路は環境で変わる）", where="smoke"),
]
